### PR TITLE
Replace sqlite3 by better-sqlite3

### LINKED ISSUE #9: Store logs in SQLite3
Our current log is cobbled together (see https://github.com/IMA-WorldHealth/clownfish/issues/2) and doesn't include nearly enough information.  We need to improve it in the following ways:

1. It isn't sorted correctly.  We need to have the data in descending order from the date the log was made - e.g. the most recent record to the last record.
2. We need to store more information - the email address sending the message, the email address receiving the message, the google drive folder id, a timestamp, whether the operation succeeded or failed,  and the overall duration.
3. It would be ideal to store this information in a format that is easy to transport and use.  SQLite3 is a good tool for this job.  It is environment-independent and gives us a single file to copy around and analyze.

I propose we install [`better-sqlite3`](https://www.npmjs.com/package/better-sqlite3) as the backend to store our log lines in.

To complete this issue, a developer will need to:

1. Install `better-sqlite3` and add it to the application.
2. Analyze the mailgun response object to find the information we need.
3. Create a `schema.sql` file to build the log table in sqlite3 when installing for the first time.
4. Add the queries to write a log line to the database on each log entry.

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR replace `sqlite3` by `better-sqlite3`.

Closes #9.

### CODE REVIEW

File: logger.js [hunk 1]
```diff
@@ -1,89 +1,75 @@
...
-          end TEXT,
-          elapsed TEXT
-        )`);
 
-      this.db.run(`
-        INSERT INTO logger (googleDriveParentFolderId, normalizedStructure, normalizedReportName, attachments, start, sender, end, elapsed)
-        VALUES ($googleDriveParentFolderId, $normalizedStructure, $normalizedReportName, $attachments, $start, $sender, $end, $elapsed)
-      `, parameters);
-    });
+    const createLoggerTableQuery = `
```
Comment (jniles) [inline logger.js]: Let's move this statement into the `constructor()`.  We only really want to execute it once when you start the application, and not on every log.

File: logger.js [hunk 2]
```diff
@@ -1,89 +1,75 @@
...
+      VALUES ($googleDriveParentFolderId, $normalizedStructure, $normalizedReportName, $attachments, $start, $sender, $end, $elapsed)
+    `;
+
+    this.db
+      .prepare(insertIntoLoggerQuery)
+      .run(parameters);
   }
 
   read(n) {
     return new Promise((resolve, reject) => {
```
Comment (jniles) [inline logger.js]: Since `better-sqlite3` is synchronous, let's get rid of the promise.  We can just directly run the code synchronously.  It should make this code a lot nicer to read. :)
